apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
  type: LoadBalancer
  loadBalancerIP: 192.168.0.202
  ports:
    - name: http-portainer
      protocol: TCP
      port: 80
      targetPort: http
